/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAulasRouteImport } from './routes/_authenticated/aulas'
import { Route as AuthenticatedBibliaRouteImport } from './routes/_authenticated/biblia'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedLectioRouteImport } from './routes/_authenticated/lectio'
import { Route as AuthenticatedReflexoesRouteImport } from './routes/_authenticated/reflexoes'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAulasRoute = AuthenticatedAulasRouteImport.update({
  id: '/aulas',
  path: '/aulas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBibliaRoute = AuthenticatedBibliaRouteImport.update({
  id: '/biblia',
  path: '/biblia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLectioRoute = AuthenticatedLectioRouteImport.update({
  id: '/lectio',
  path: '/lectio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReflexoesRoute = AuthenticatedReflexoesRouteImport.update({
  id: '/reflexoes',
  path: '/reflexoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/aulas': typeof AuthenticatedAulasRoute
  '/biblia': typeof AuthenticatedBibliaRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/lectio': typeof AuthenticatedLectioRoute
  '/reflexoes': typeof AuthenticatedReflexoesRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/aulas': typeof AuthenticatedAulasRoute
  '/biblia': typeof AuthenticatedBibliaRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/lectio': typeof AuthenticatedLectioRoute
  '/reflexoes': typeof AuthenticatedReflexoesRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/aulas': typeof AuthenticatedAulasRoute
  '/_authenticated/biblia': typeof AuthenticatedBibliaRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/lectio': typeof AuthenticatedLectioRoute
  '/_authenticated/reflexoes': typeof AuthenticatedReflexoesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/aulas'
    | '/biblia'
    | '/historico'
    | '/lectio'
    | '/reflexoes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/reset-password'
    | '/aulas'
    | '/biblia'
    | '/historico'
    | '/lectio'
    | '/reflexoes'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/aulas'
    | '/_authenticated/biblia'
    | '/_authenticated/historico'
    | '/_authenticated/lectio'
    | '/_authenticated/reflexoes'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aulas': {
      id: '/_authenticated/aulas'
      path: '/aulas'
      fullPath: '/aulas'
      preLoaderRoute: typeof AuthenticatedAulasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/biblia': {
      id: '/_authenticated/biblia'
      path: '/biblia'
      fullPath: '/biblia'
      preLoaderRoute: typeof AuthenticatedBibliaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lectio': {
      id: '/_authenticated/lectio'
      path: '/lectio'
      fullPath: '/lectio'
      preLoaderRoute: typeof AuthenticatedLectioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reflexoes': {
      id: '/_authenticated/reflexoes'
      path: '/reflexoes'
      fullPath: '/reflexoes'
      preLoaderRoute: typeof AuthenticatedReflexoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAulasRoute: typeof AuthenticatedAulasRoute
  AuthenticatedBibliaRoute: typeof AuthenticatedBibliaRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedLectioRoute: typeof AuthenticatedLectioRoute
  AuthenticatedReflexoesRoute: typeof AuthenticatedReflexoesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAulasRoute: AuthenticatedAulasRoute,
  AuthenticatedBibliaRoute: AuthenticatedBibliaRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedLectioRoute: AuthenticatedLectioRoute,
  AuthenticatedReflexoesRoute: AuthenticatedReflexoesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
