// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nskkewnywjgqlvhbyrmv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5za2tld255d2pncWx2aGJ5cm12Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTE0NDEwNjIsImV4cCI6MjEwNzAxNzA2Mn0.YC-4s42nQGJxXg8FmfD1Fj3TOM5bw0HlMjQ9xoMzXIU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});